### PR TITLE
Finished guitar.py for Guitar Palpatine and Mr. Steeltastic

### PR DESCRIPTION
**Pull request by PickleFace5**
This should be the last commits for guitar.py unless some issue comes up. Yipeeeee.

### CODE REVIEW

**Review by reklawn — CHANGES_REQUESTED** [review]
Looks fine, but there are a few indentation mistakes, for the sub-classes and for some functions. This can affect the hierarchy and you may run into code errors.

**Comment by PickleFace5** [comment]
That should've fixed any formatting issues.

**Review by reklawn — COMMENTED** [review]
Looks fine. You may want to run the code to ensure all formatting. Once that's done I will approve. (This may also just be the app)

**Review by PickleFace5 — COMMENTED** [review]
Ran it in sim, no crashes or errors. Seems good.

**Review by reklawn — APPROVED** [review]

**Pull request merged**
